#!/bin/bash
# http://stackoverflow.com/questions/1466709/improve-my-password-generation-script

LEN=24
RND=/dev/urandom
alpha=`echo {a..z} | tr -d ' '`
ALPHA=`echo {A..Z} | tr -d ' '`
NUM=`echo {0..9} | tr -d ' '`
SYM="!@$%&(){}?"
# GENERATES ONE (1) RANDOM LOWERCASE LETTER!
until [ $(echo $first | grep [$alpha] ) ]; do
    first=$(cat $RND | LC_CTYPE=C tr -cd "$alpha" | head -c 1)
done

# CAPTURES OPTIONS (e.g. -c & -l) AND ARGUMENTS (e.g. l,u,n & s)!
while getopts "c:l:" opt; do
    case "${opt}" in
        c) args=$OPTARG ;;
        l) LEN=$OPTARG ;;
    esac
done

# EVALUATES THE '$args' VARIABLE, WHICH CONSIST OF THE ARGUMENTS FROM THE '-c' OPTION,
# AND ASSIGN IT A NUMERICAL VALUE TO BE USED IN FUTURE 'IF' STATEMENTS!
count=$(expr ${#args} - 1)
for i in $(seq 0 $count)
do
    init=${args:$i:1}
    if [ "$init" == "l" ]; then a=1
    elif [ "$init" == "u" ]; then b=3
    elif [ "$init" == "n" ]; then c=5
    elif [ "$init" == "s" ]; then d=11
    fi
done
sum=$((a + b + c + d))


# LOWERCASE LETTERS ONLY!
if ( [[ "$sum" == "1" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$alpha] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$alpha" | head -c $LEN)
    done
echo -e $pass '\n'

# UPPERCASE LETTERS ONLY!
elif ( [[ "$sum" == "3" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$ALPHA] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA" | head -c $LEN)
    done
echo -e $pass '\n'

# NUMBERS ONLY!
elif ( [[ "$sum" == "5" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$NUM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$NUM" | head -c $LEN)
    done
echo -e $pass '\n'

# SYMBOLS ONLY!
elif ( [[ "$sum" == "11" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$SYM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$SYM" | head -c $LEN)
    done
echo -e $pass '\n'


# LOWERCASE & UPPERCASE LETTERS!
elif ( [[ "$sum" == "4" && "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$ALPHA] ) ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA" | head -c $LEN)"
    done
echo -e $pass '\n'

# LOWERCASE LETTERS & NUMBERS!
elif ( [[ "$sum" == "6" && "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$NUM] ) ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$NUM" | head -c $LEN)"
    done
echo -e $pass '\n'

# UPPERCASE LETTERS & NUMBERS!
elif ( [[ "$sum" == "8" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$ALPHA] | grep [$NUM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA$NUM" | head -c $LEN)
    done
echo -e $pass '\n'

# LOWERCASE LETTERS & SYMBOLS!
elif ( [[ "$sum" == "12" && "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$SYM] ) ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$SYM" | head -c $LEN)"
    done
echo -e $pass '\n'

# UPPERCASE LETTERS & SYMBOLS!
elif ( [[ "$sum" == "14" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$ALPHA] | grep [$SYM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA$SYM" | head -c $LEN)
    done
echo -e $pass '\n'

# NUMBERS & SYMBOLS!
elif ( [[ "$sum" == "16" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$NUM] | grep [$DIGIT] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$CHAR$DIGIT" | head -c $LEN)
    done
echo -e $pass '\n'


# LOWERCASE, UPPERCASE LETTERS & NUMBERS!
elif ( [[ "$sum" == "9" && "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$ALPHA] | grep [$NUM] ) ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$NUM" | head -c $LEN)"
    done
echo -e $pass '\n'

# LOWERCASE, UPPERCASE LETTERS & SYMBOLS!
elif ( [[ "$sum" == "15" && "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$ALPHA] | grep [$SYM] ) ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$SYM" | head -c $LEN)"
    done
echo -e $pass '\n'

# LOWERCASE LETTERS, NUMBERS & SYMBOLS!
elif ( [[ "$sum" == "17" && "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$NUM] | grep [$SYM] ) ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$NUM$SYM" | head -c $LEN)"
    done
echo -e $pass '\n'

# UPPERCASE LETTERS, NUMBERS & SYMBOLS!
elif ( [[ "$sum" == "19" && "$LEN" -gt 11 ]] ); then
    until [ $(echo $pass | grep [$ALPHA] | grep [$NUM] | grep [$SYM] ) ]; do
        pass=$(cat $RND | LC_CTYPE=C tr -cd "$ALPHA$NUM$SYM" | head -c $LEN)
    done
echo -e $pass '\n'


# ALL OR NO '-c' OPTION!
elif ( [[ -z $args ]] || [[ "$sum" == "20" ]] && [[ "$LEN" -gt 11 ]] ); then
    LEN=`expr $LEN - 1`
    until [ $(echo $pass | grep [$alpha] | grep [$ALPHA] | grep [$NUM] | grep -c [$SYM] ) == 1 ]; do
        pass="$first$(cat $RND | LC_CTYPE=C tr -cd "$alpha$ALPHA$NUM$SYM" | head -c $LEN)"
    done
    echo -e $pass '\n';

else
    echo -e "Length option (i.e. -l) MUST HAVE an argument greather than eleven (11)!\n"
fi
